name: Build and Push to GHCR

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build backend image
        run: docker build -t ghcr.io/holbok-peti/laravel:latest ./DockerBeadandoBackend

      - name: Push backend image
        run: docker push ghcr.io/holbok-peti/laravel:latest

      - name: Build frontend image
        run: docker build -t ghcr.io/holbok-peti/angular:latest ./DockerBeadandoFrontend

      - name: Push frontend image
        run: docker push ghcr.io/holbok-peti/angular:latest